# Generated by Django 2.2.6 on 2019-10-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(max_length=50)),
                ('results', models.IntegerField(default=100)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
