# Generated by Django 2.2.6 on 2019-10-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='brands',
            field=models.TextField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quote',
            name='items_lazada',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quote',
            name='items_shopee',
            field=models.IntegerField(default=0),
        ),
    ]
